### ISSUE TITLE
can not run quantum_transfer_learning example

### ISSUE THREAD

**Issue by jianqingzhu** [JDEA-Quantum-Lab/TeD-Q#1]
Dear Xingyao Wu,
    I meet troubles when running the quantum_transfer_learning, as follows
   

errors: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
tools: py3.8, torch.1.11, cuda 11, RTX3090

**Comment by yaochengchen** [comment]
I am using python 3.8.10, torch=1.11.0, ray=1.6.0, and I don't have any problems of running all the examples. Have you install "ray" ?
![image](https://user-images.githubusercontent.com/51320658/176234916-150ad958-a60c-400a-8ce0-0b286d52bb35.png)

**Comment by jianqingzhu** [comment]
您好，感谢回复。我有安装ray，应该就是JDtensorPath出错了，不知道为什么。

---Original---
From: ***@***.***&gt;
Date: Wed, Jun 29, 2022 00:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JDEA-Quantum-Lab/TeD-Q] can not run quantum_transfer_learningexample (Issue #1)




 
I am using python 3.8.10, torch=1.11.0, ray=1.6.0, and I don't have any problems of running all the examples. Have you install "ray" ?

**Comment by TuringTW** [comment]
Hi, could you provide the error log? Let's find out what the problem is.
