### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Dongyang20222022** [JDEA-Quantum-Lab/TeD-Q#2]
感觉TeD-Q的模块设计和代码逻辑基本都照搬PennyLane。比如这里面的[Quantum_transfer_learning教程](https://github.com/JDEA-Quantum-Lab/TeD-Q/blob/main/examples/Quantum_transfer_learning.ipynb)，和PennyLane的[Quantum_transfer_learning教程](https://pennylane.ai/qml/demos/tutorial_quantum_transfer_learning.html)相似度太高了，说是抄袭也不为过啊。。而且连人家的代码注释都完全照搬。。比如PennyLane是这样定义VQC的：
<img width="734" alt="屏幕快照 2022-06-30 上午10 05 22" src="https://user-images.githubusercontent.com/103877855/176577315-238dc395-9b02-4ba1-a6d9-bbaef2a34107.png">
再看看TeD-Q定义的VQC：
<img width="693" alt="屏幕快照 2022-06-30 上午10 05 02" src="https://user-images.githubusercontent.com/103877855/176577353-667ee95a-1b2c-431c-a438-7e7ca18d65c3.png">

如果TeD-Q基本就是PennyLane的复制，这样就是真的没意思了啊。。

**Comment by yaochengchen** [comment]
睁开你的眼睛好好看看这个说明。我们这个例子就是引用跟 pennylane 一样的例子。说明里已经很明白的说了。我们也有自己原创的例子。有相同的例子这样才更方便大家比较不是吗？
![image](https://user-images.githubusercontent.com/51320658/176595968-eb1bef63-a757-4506-bf52-be68136a3121.png)

**Comment by yaochengchen** [comment]
要是我们模块设置跟代码逻辑都是抄袭 pennylane 的，那在 Many_body_Localization 例子上，我们怎么能取得比 pennylane 运算速度快很多的结果？你可以去运行 examples/comparison 里的代码，然后看看速度对比。
![image](https://user-images.githubusercontent.com/51320658/176596830-a28fb6db-df55-4bac-980e-20dfa0c1adec.png)
